---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
spec:
  ingressClassName: "nginx"
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /whoami
            backend:
              service:
                name: whoami
                port:
                  number: 8080
